// 지역 한영 이름 매핑 (area-codes.ts의 AREA_CODES 기준)

export const REGION_NAME_EN: Record<string, string> = {
  "11":    "Seoul",
  "26":    "Busan",
  "27":    "Daegu",
  "28":    "Incheon",
  "29":    "Gwangju",
  "30":    "Daejeon",
  "31":    "Ulsan",
  "41":    "Gyeonggi",
  "43":    "Chungbuk",
  "44":    "Chungnam",
  "46":    "Jeonnam",
  "47":    "Gyeongbuk",
  "48":    "Gyeongnam",
  "50":    "Jeju",
  "51":    "Gangwon",
  "52":    "Jeonbuk",
  "36110": "Sejong",
};

export const REGION_NAME_KO: Record<string, string> = {
  "11":    "서울",
  "26":    "부산",
  "27":    "대구",
  "28":    "인천",
  "29":    "광주",
  "30":    "대전",
  "31":    "울산",
  "41":    "경기",
  "43":    "충북",
  "44":    "충남",
  "46":    "전남",
  "47":    "경북",
  "48":    "경남",
  "50":    "제주",
  "51":    "강원",
  "52":    "전북",
  "36110": "세종",
};
